services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/letsencrypt:/etc/letsencrypt
      - ./nginx/maintenance.html:/usr/share/nginx/html/maintenance.html
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - saam-backend
      - saam-frontend
    networks:
      - saam-network

  saam-frontend:
    image: ardilan13/saam:frontend
    deploy:
      replicas: 2
    networks:
      - saam-network

  saam-backend:
    image: ardilan13/saam:backend
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - APP_DATABASE_URI=${APP_DATABASE_URI}
      - MAILTRAP_HOST=${MAILTRAP_HOST}
      - MAILTRAP_TOKEN=${MAILTRAP_TOKEN}
      - MAILTRAP_SENDER_NAME=${MAILTRAP_SENDER_NAME}
      - MAILTRAP_SENDER_EMAIL=${MAILTRAP_SENDER_EMAIL}
      - DAYJS_START=${DAYJS_START}
      - DAYJS_END=${DAYJS_END}
      - ACADEMIC_YEAR=${ACADEMIC_YEAR}
      - ACADEMIC_TERM=${ACADEMIC_TERM}
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - saam-network

networks:
  saam-network:
    driver: overlay