# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/saam.uis.edu.co
cert = /etc/letsencrypt/live/saam.uis.edu.co/cert.pem
privkey = /etc/letsencrypt/live/saam.uis.edu.co/privkey.pem
chain = /etc/letsencrypt/live/saam.uis.edu.co/chain.pem
fullchain = /etc/letsencrypt/live/saam.uis.edu.co/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 70e398e5932a524c70b49a3bba944052
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
