# Balanceador del backend
upstream saam_backend {
    server saam-backend:3000;
}

# Balanceador del frontend
upstream saam_frontend {
    server saam-frontend:5173;
}

server {
    listen 443 ssl;
    server_name saam.uis.edu.co;

    ssl_certificate /etc/letsencrypt/live/saam.uis.edu.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/saam.uis.edu.co/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Ruta para el frontend
    location / {
        # proxy_pass http://saam_frontend;
        # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
        # proxy_cache_bypass $http_upgrade;
        root /usr/share/nginx/html;
        index maintenance.html;
    }

    # Ruta para el backend
    location /api/ {
        proxy_pass http://saam_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
}